### ISSUE TITLE
URIs in Bash/PowerShell are incorrect

### ISSUE THREAD

**Issue by samaea** [mrajess/Azure-Policy-CIS#10]
For example, in the policy 1.23(https://github.com/mrajess/Azure-Policy-CIS/tree/master/policies/1_identity_and_access-management/1.23/Policy) 

"**https://raw.githubusercontent.com/mrajess/Azure-Policy-CIS/master/policies/1_identity_and_access-management/1.23/Deny/azurepolicy.rules.json**" should be "**https://raw.githubusercontent.com/mrajess/Azure-Policy-CIS/master/policies/1_identity_and_access-management/1.23/Policy/azurepolicy.rules.json**".

**Comment by mrajess** [comment]
Ha! Thanks for pointing that out. I forgot to change all of that. I'm working on a major addition to section 5 right now and I'll be sure to include the fixes to the readme's in that PR. :)

**Comment by mrajess** [comment]
For the time being I'm pulling all of the CLI and PS examples out of the readmes until I've finished the rest of the policies.
