### ISSUE TITLE
Regarding the field

### ISSUE THREAD

**Issue by pinaki1234** [mrajess/Azure-Policy-CIS#6]
Hi 
Are you sure this field is a valid one:

"field": "Microsoft.Storage/storageAccounts/blobServices/default.containers.publicAccess",

Trying to create the policy with this field as above but it is not getting recognized.

**Comment by mrajess** [comment]
This has now been fixed. The alias changed from when I first wrote it. The updated alias is: Microsoft.Storage/storageAccounts/blobServices/containers/publicAccess
